version: "3.8"
services:
  app:
    container_name: "bookmarkAPI"
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/bookmark
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres_db

  postgres_db:
    container_name: "postgresdb"
    image: "postgres"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "bookmark"

volumes:
  postgres-data: